nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  "@testing-library/jest-dom@*":
    dependencies:
      jest-dom: ^4.0.0
